# Generated by Django 5.0.1 on 2024-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_home_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('yourmessage', models.CharField(max_length=1150)),
            ],
        ),
    ]
