# Generated by Django 5.0.1 on 2024-02-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serv',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='serv',
            old_name='name',
            new_name='names',
        ),
    ]
